language: php

php:
  - 7.0

env:
  global:
    - setup=basic

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi
  - npm install -g npm@'>=2.1.9'
  - npm install -g gulp
  - travis_retry npm install
  - travis_retry gulp

services:
  - mysql

before_script:
  - mysql -e 'create database if not exists tourney;'
  - php artisan migrate:install --no-interaction

script:
  - php artisan migrate --no-interaction
  - gulp test

notifications:
    on_success: never
    on_failure: never
