language: php

php:
  - 7.0

env:
  global:
    - setup=basic

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

services:
  - mysql

before_script:
  - mysql -e 'create database tourney;'
  - php artisan migrate:install --no-interaction -vvv

script:
  - php artisan migrate --no-interaction -vvv
  - phpunit

notifications:
    on_success: never
    on_failure: always
