language: php

php:
  - 7.0

services:
  - mysql

before_script:
  - mysql -e 'create database tourney;'
  - composer self-update
  - travis_retry composer install --no-interaction -vvv
  - npm install -g npm@'>=2.1.9'
  - npm install
  - gulp

script:
  - php artisan migrate --no-interaction -vvv
  - gulp test

notifications:
    on_success: never
    on_failure: never
