language: php

php:
  - 7.0

before_script:
  - mysql -e 'drop database if exists tourney;'
  - mysql -e 'create database tourney;'
  - composer self-update
  - composer install --no-install
  - php artisan migrate:install --no-interaction -vvv
  - npm install -g npm@'>=2.1.9'
  - npm install
  - gulp

services:
  - mysql

script:
  - php artisan migrate --no-interaction -vvv
  - gulp test

notifications:
    on_success: never
    on_failure: never
